version: "3.9"

services:
  db:
    image: postgres:15
    env_file:
      - .env # файл с POSTGRES_* и DATABASE_URL (при необходимости)
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./nuxt-app
      dockerfile: Dockerfile
    env_file:
      - ./nuxt-app/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db-data:
