version: "3.9"

services:
  app:
    build:
      context: ./nuxt-app
      dockerfile: Dockerfile
    command: >
      sh -c "
        ./wait-for-db.sh &&
        npx prisma db push --accept-data-loss &&
        npm run dev
      "
    volumes:
      - ./nuxt-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
